name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Create a major (breaking changes), minor (new features) or patch (fixes) release'
        options:
          - patch
          - minor
          - major
        default: patch
      pre-release:
        description: 'Set as a pre-release'
        required: false
        type: boolean

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required for the action to be able to see all tags

      - name: Bump version and push tag
        id: bump_version
        run: |
          # Aquí puedes agregar tu script personalizado para incrementar la versión
          # y crear una nueva etiqueta. Asegúrate de exponer la nueva etiqueta como
          # una variable de entorno para que pueda ser utilizada en los siguientes pasos.
          echo "TAG_NAME=v1.0.0" >> $GITHUB_ENV  # reemplaza esto con tu lógica de incremento de versión

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # required
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: ${{ github.event.inputs.pre-release }}
          prerelease: ${{ github.event.inputs.pre-release }}
