name: Bump Version

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice
        description: 'Create a major (breaking changes), minor (new features) or patch (fixes) release'
        options:
          - patch
          - minor
          - major
        default: patch
      pre-release:
        description: 'Set as a pre-release'
        required: false
        type: boolean

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required for the action to be able to see all tags

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.34.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # required
          WITH_V: true  # optional, adds 'v' prefix to tag name
          DEFAULT_BUMP: ${{ github.event.inputs.bump }}  # set the bump type based on the input
          DRY_RUN: false  # optional, defaults to 'false'
          TAG_CONTEXT: repo  # optional, one of: repo, branch. 'branch' will create a new tag each push to a branch.

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # required
        with:
          tag_name: ${{ steps.bump_version.outputs.tag }}
          release_name: Release ${{ steps.bump_version.outputs.tag }}
          draft: ${{ github.event.inputs.pre-release }}
          prerelease: ${{ github.event.inputs.pre-release }}
